### ISSUE TITLE
blog/bad-interpreter-error-jupyter/

### ISSUE THREAD

**Issue by allenfrostline** [allenfrostline/allenfrostline.github.io#24]
https://allenfrostline.com/blog/bad-interpreter-error-jupyter/

**Comment by kallewesterling** [comment]
Thank you! Saved my life!

**Comment by allenfrostline** [comment]
> @kallewesterling
> Thank you! Saved my life!

Glad it helped 😁

**Comment by N3TBOY** [comment]
Thanks!
