### ISSUE TITLE
blog/epidemic-models/

### ISSUE THREAD

**Issue by allenfrostline** [allenfrostline/allenfrostline.github.io#90]
https://allenfrostline.com/blog/epidemic-models/

**Comment by antgolovanov** [comment]
With fatality rate = 2.5% and resuspectibility = 0% (lifelong immunity) how can population size become lower than 97.5% within a year? Even if anyone gets sick?

**Comment by allenfrostline** [comment]
> @antgolovanov
> With fatality rate = 2.5% and resuspectibility = 0% (lifelong immunity) how can population size become lower than 97.5% within a year? Even if anyone gets sick?

Good point. I think that's due to the fact that, like the other rates, the "fatality rate" here I'm using is defined per unit time, too. That is to say, I'm assuming 2.5% deaths among all infectious people ***per day***. That's an extremely exaggerated rate cuz as of now the total death rate due to 2019-nCoV is just above 2%, giving v< 0.2% from time series regression — which, however, is still terrifying as it cumulates deaths exponentially over time.

As a result, I've just changed the range of the v-slider to [0, 0.5%] so the plot is more realistic. You can now toggle the sliders to 0% resusceptibility and 0.17% fatality, which would resemble the current 2019-nCoV growth.

**Comment by antgolovanov** [comment]
Thanks Allen, it’s really a daily fatality rate, clear from the equations, I missed it.
Great job!

> @allenfrostline
> > @antgolovanov
> > With fatality rate = 2.5% and resuspectibility = 0% (lifelong immunity) how can population size become lower than 97.5% within a year? Even if anyone gets sick?
> 
> Good point. I think that's due to the fact that, like the other rates, the "fatality rate" here I'm using is defined per unit time, too. That is to say, I'm assuming 2.5% deaths among all infectious people ***per day***. That's an extremely exaggerated rate cuz as of now the total death rate due to 2019-nCoV is just above 2%, giving v< 0.2% from time series regression — which, however, is still terrifying as it cumulates deaths exponentially over time.
> 
> As a result, I've just changed the range of the v-slider to [0, 0.5%] so the plot is more realistic. You can now toggle the sliders to 0% resusceptibility and 0.17% fatality, which would resemble the current 2019-nCoV growth.

**Comment by zzfu** [comment]
王桑好久没发blog了

**Comment by allenfrostline** [comment]
> @zzfu
> 王桑好久没发blog了

这不是这几个月616加班加到死吗（
